#!/bin/bash

set -euo pipefail

platform="${PLATFORM:-linux}"
exeext=""
if [ "$platform" = "windows" ]; then
    exeext=".exe"
fi

make PLATFORM="$platform" tests
build/bin/$platform/test_core$exeext
build/bin/$platform/test_hebi$exeext
build/bin/$platform/test_kuma$exeext
build/bin/$platform/test_ookami$exeext
build/bin/$platform/test_sokko$exeext
build/bin/$platform/test_usagi$exeext
build/bin/$platform/test_poni$exeext
build/bin/$platform/test_tora$exeext
build/bin/$platform/test_neko$exeext
