
/* AI GENERATED TEST SUITE */

// Everything here looks good to me, but note this was generated by an LLM.
// More tests might be warranted if using for production.

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
#include "hebi.h"
#include "sokko.h"
#include "usagi.h"
#include "tora.h"

/* ---------- Test infrastructure ---------- */

static int testsRun = 0;
static int testsPassed = 0;

#define CHECK(cond, name) do { \
    testsRun++; \
    if (cond) { testsPassed++; printf("  [PASS] %s\n", name); } \
    else { printf("  [FAIL] %s (line %d)\n", name, __LINE__); } \
} while (0)

#define SECTION(name) printf("\n=== %s ===\n", name)

static double realOf(MatrixElement e) {
    return e.isComplex ? e.value.complex.real : e.value.real;
}

static bool approxReal(MatrixElement e, double expected, double tol) {
    double actual = realOf(e);
    return fabs(actual - expected) <= tol;
}

/* ---------- ConjugacyClass tests ---------- */

void testConstructAndFreeConjugacyClass() {
    SECTION("constructConjugacyClass / freeConjugacyClass");
    Group* Z4 = constructZnGroup(4);

    // NULL inputs
    CHECK(constructConjugacyClass(NULL, Z4->elements[0]) == NULL, "construct: NULL group");
    CHECK(constructConjugacyClass(Z4, NULL) == NULL, "construct: NULL rep");

    // Identity is its own class in any group
    ConjugacyClass* cls = constructConjugacyClass(Z4, Z4->elements[0]);
    CHECK(cls != NULL, "construct identity class");
    CHECK(cls->group == Z4, "class group pointer");
    CHECK(cls->rep == Z4->elements[0], "class rep pointer");
    CHECK(cls->size == 1, "identity class size is 1");
    CHECK(cls->elementOrder == 1, "identity element order is 1");
    CHECK(cls->indices != NULL, "class indices allocated");
    freeConjugacyClass(cls);

    // element of order 2 in Z4
    ConjugacyClass* cls2 = constructConjugacyClass(Z4, Z4->elements[2]);
    CHECK(cls2 != NULL, "construct order-2 class");
    CHECK(cls2->size == 1, "Z4: each class has size 1 (abelian)");
    CHECK(cls2->elementOrder == 2, "element 2 has order 2 in Z4");
    freeConjugacyClass(cls2);

    // free(NULL) should be safe
    freeConjugacyClass(NULL);
    CHECK(1, "freeConjugacyClass(NULL) does not crash");

    freeGroup(Z4);
}

void testGetConjugacyClass() {
    SECTION("getConjugacyClass");
    Group* Z3 = constructZnGroup(3);

    CHECK(getConjugacyClass(NULL) == NULL, "getConjugacyClass: NULL");

    ConjugacyClass* cls = getConjugacyClass(Z3->elements[1]);
    CHECK(cls != NULL, "getConjugacyClass produces class");
    CHECK(cls->rep == Z3->elements[1], "class rep matches");
    CHECK(cls->size == 1, "Z3 abelian: class size 1");
    freeConjugacyClass(cls);

    freeGroup(Z3);
}

void testGetConjugacyClasses() {
    SECTION("getConjugacyClasses");
    int n;

    CHECK(getConjugacyClasses(NULL, &n) == NULL, "NULL group");

    // Abelian: every element is its own class
    Group* Z5 = constructZnGroup(5);
    ConjugacyClass** classes = getConjugacyClasses(Z5, &n);
    CHECK(classes != NULL, "Z5: got classes");
    CHECK(n == 5, "Z5: has 5 conjugacy classes");
    int totalSize = 0;
    for (int i = 0; i < n; i++) totalSize += classes[i]->size;
    CHECK(totalSize == 5, "Z5: sum of class sizes = |G|");
    for (int i = 0; i < n; i++) freeConjugacyClass(classes[i]);
    free(classes);
    freeGroup(Z5);

    // S_3: 3 conjugacy classes of sizes 1, 3, 2
    Group* S3 = constructSymmetricGroup(3);
    classes = getConjugacyClasses(S3, &n);
    CHECK(classes != NULL, "S3: got classes");
    CHECK(n == 3, "S3: has 3 conjugacy classes");
    int sum = 0;
    for (int i = 0; i < n; i++) sum += classes[i]->size;
    CHECK(sum == 6, "S3: sum of class sizes = 6");
    for (int i = 0; i < n; i++) freeConjugacyClass(classes[i]);
    free(classes);
    freeGroup(S3);
}

/* ---------- Representation tests ---------- */

// Build a small Matrix** manually for testing construct/free
static Matrix** makeIdentityImages(int count, int dim) {
    Matrix** imgs = malloc(count * sizeof(Matrix*));
    for (int i = 0; i < count; i++) imgs[i] = idMatrix(dim);
    return imgs;
}

void testConstructAndFreeRepresentation() {
    SECTION("constructRepresentation / freeRepresentation");
    Group* Z2 = constructZnGroup(2);

    CHECK(constructRepresentation(NULL, "X", NULL, 1, 1) == NULL, "NULL inputs");

    Matrix** imgs = makeIdentityImages(Z2->card, 2);
    Representation* rep = constructRepresentation(Z2, "Test", imgs, 2, 2);
    CHECK(rep != NULL, "rep constructed");
    CHECK(rep->group == Z2, "rep->group correct");
    CHECK(rep->images == imgs, "rep->images correct");
    CHECK(rep->mdim == 2, "rep->mdim set");
    CHECK(rep->dim == 2, "rep->dim set");
    CHECK(strcmp(rep->repr, "Test") == 0, "rep->repr copied");
    freeRepresentation(rep);

    freeRepresentation(NULL);
    CHECK(1, "freeRepresentation(NULL) safe");

    freeGroup(Z2);
}

void testTrivialRepresentation() {
    SECTION("trivialRepresentation");
    CHECK(trivialRepresentation(NULL) == NULL, "NULL group");

    Group* Z4 = constructZnGroup(4);
    Representation* rep = trivialRepresentation(Z4);
    CHECK(rep != NULL, "rep built");
    CHECK(rep->dim == 1, "trivial dim = 1");
    CHECK(rep->mdim == 1, "trivial mdim = 1");
    for (int i = 0; i < Z4->card; i++) {
        CHECK(approxReal(getEntry(rep->images[i], 0, 0), 1.0, 1e-12),
              "trivial image is [1]");
    }
    freeRepresentation(rep);
    freeGroup(Z4);
}

void testRegularRepresentation() {
    SECTION("regularRepresentation");
    CHECK(regularRepresentation(NULL) == NULL, "NULL group");

    Group* Z3 = constructZnGroup(3);
    Representation* rep = regularRepresentation(Z3);
    CHECK(rep != NULL, "rep built");
    CHECK(rep->dim == 3, "regular dim = |G|");
    CHECK(rep->mdim == 3, "regular mdim = |G|");

    // Identity image should be the identity matrix
    Matrix* I = rep->images[0];
    bool identityOk = true;
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++) {
            double expected = (i == j) ? 1.0 : 0.0;
            if (!approxReal(getEntry(I, i, j), expected, 1e-12)) identityOk = false;
        }
    CHECK(identityOk, "regular rep of identity is I");

    // Each image is a permutation matrix: each row/col has exactly one 1
    bool permOk = true;
    for (int g = 0; g < Z3->card; g++) {
        for (int i = 0; i < 3; i++) {
            int rowOnes = 0, colOnes = 0;
            for (int j = 0; j < 3; j++) {
                if (approxReal(getEntry(rep->images[g], i, j), 1.0, 1e-12)) rowOnes++;
                if (approxReal(getEntry(rep->images[g], j, i), 1.0, 1e-12)) colOnes++;
            }
            if (rowOnes != 1 || colOnes != 1) permOk = false;
        }
    }
    CHECK(permOk, "each regular image is a permutation matrix");

    freeRepresentation(rep);
    freeGroup(Z3);
}

void testPermutationRepresentation() {
    SECTION("permutationRepresentation");
    CHECK(permutationRepresentation(NULL) == NULL, "NULL group");

    // S_3: permutation rep should have dim equal to index of the largest core-free subgroup (= 3)
    Group* S3 = constructSymmetricGroup(3);
    Representation* rep = permutationRepresentation(S3);
    CHECK(rep != NULL, "S3: perm rep built");
    CHECK(rep->dim >= 1 && rep->dim <= S3->card, "S3: perm rep dim sensible");

    // Identity element must map to identity matrix
    Matrix* I = rep->images[0];
    bool identityOk = true;
    for (int i = 0; i < rep->dim; i++)
        for (int j = 0; j < rep->dim; j++) {
            double expected = (i == j) ? 1.0 : 0.0;
            if (!approxReal(getEntry(I, i, j), expected, 1e-12)) identityOk = false;
        }
    CHECK(identityOk, "S3: perm rep of identity is I");
    freeRepresentation(rep);
    freeGroup(S3);
}

void testStandardRepresentation() {
    SECTION("standardRepresentation");
    CHECK(standardRepresentation(NULL) == NULL, "NULL group");

    Group* S3 = constructSymmetricGroup(3);
    Representation* rep = standardRepresentation(S3);
    CHECK(rep != NULL, "S3: standard rep built");
    // Standard rep of S_n has dim n-1; with perm rep dim 3 we expect dim 2
    CHECK(rep->dim >= 1, "S3: standard dim >= 1");

    // Identity must still be identity
    Matrix* I = rep->images[0];
    bool identityOk = true;
    for (int i = 0; i < rep->dim; i++)
        for (int j = 0; j < rep->dim; j++) {
            double expected = (i == j) ? 1.0 : 0.0;
            if (!approxReal(getEntry(I, i, j), expected, 1e-12)) identityOk = false;
        }
    CHECK(identityOk, "S3: standard rep of identity is I");

    freeRepresentation(rep);
    freeGroup(S3);
}

/* ---------- Character tests ---------- */

void testConstructAndFreeCharacter() {
    SECTION("constructCharacter / freeCharacter");
    Group* Z3 = constructZnGroup(3);
    int n;
    ConjugacyClass** classes = getConjugacyClasses(Z3, &n);
    ComplexNumber* values = malloc(n * sizeof(ComplexNumber));
    for (int i = 0; i < n; i++) { values[i].real = 1.0; values[i].imag = 0.0; }

    CHECK(constructCharacter(NULL, "x", classes, values, n) == NULL, "NULL group");
    CHECK(constructCharacter(Z3, NULL, classes, values, n) == NULL, "NULL repr");
    CHECK(constructCharacter(Z3, "x", NULL, values, n) == NULL, "NULL classes");
    CHECK(constructCharacter(Z3, "x", classes, NULL, n) == NULL, "NULL values");

    Character* chi = constructCharacter(Z3, "trivial", classes, values, n);
    CHECK(chi != NULL, "character constructed");
    CHECK(chi->group == Z3, "group pointer");
    CHECK(chi->classes == classes, "classes pointer");
    CHECK(chi->values == values, "values pointer");
    CHECK(chi->numClasses == n, "numClasses stored");
    CHECK(strcmp(chi->repr, "trivial") == 0, "repr copied");

    // freeCharacter frees classes (array), values, repr — but not class contents
    // So we must free individual classes first, then let freeCharacter handle the array
    for (int i = 0; i < n; i++) freeConjugacyClass(classes[i]);
    freeCharacter(chi);

    freeCharacter(NULL);
    CHECK(1, "freeCharacter(NULL) safe");

    freeGroup(Z3);
}

/* ---------- CharacterTable tests ---------- */

void testConstructAndFreeCharacterTable() {
    SECTION("constructCharacterTable / freeCharacterTable");
    Group* Z2 = constructZnGroup(2);
    int n;
    ConjugacyClass** classes = getConjugacyClasses(Z2, &n);

    // Two irreducible characters for Z2
    int numIrreps = n;
    Character** irreps = malloc(numIrreps * sizeof(Character*));
    for (int k = 0; k < numIrreps; k++) {
        ComplexNumber* v = malloc(n * sizeof(ComplexNumber));
        for (int i = 0; i < n; i++) { v[i].real = (k == 0) ? 1.0 : ((i == 0) ? 1.0 : -1.0); v[i].imag = 0.0; }
        // Character takes ownership of v. But we also need a classes pointer — pass the shared
        // array. We will NOT let freeCharacter free the shared classes; so instead construct a
        // per-character copy of the array.
        ConjugacyClass** classesCopy = malloc(n * sizeof(ConjugacyClass*));
        for (int i = 0; i < n; i++) classesCopy[i] = classes[i];
        irreps[k] = constructCharacter(Z2, "chi", classesCopy, v, n);
    }

    ComplexNumber** values = malloc(numIrreps * sizeof(ComplexNumber*));
    for (int i = 0; i < numIrreps; i++) {
        values[i] = malloc(n * sizeof(ComplexNumber));
        for (int j = 0; j < n; j++) {
            values[i][j].real = irreps[i]->values[j].real;
            values[i][j].imag = 0.0;
        }
    }

    CHECK(constructCharacterTable(NULL, classes, irreps, values, n, numIrreps) == NULL, "NULL group");
    CHECK(constructCharacterTable(Z2, NULL, irreps, values, n, numIrreps) == NULL, "NULL classes");
    CHECK(constructCharacterTable(Z2, classes, NULL, values, n, numIrreps) == NULL, "NULL irreps");
    CHECK(constructCharacterTable(Z2, classes, irreps, NULL, n, numIrreps) == NULL, "NULL values");

    CharacterTable* table = constructCharacterTable(Z2, classes, irreps, values, n, numIrreps);
    CHECK(table != NULL, "table constructed");
    CHECK(table->group == Z2, "table group");
    CHECK(table->numClasses == n, "numClasses");
    CHECK(table->numIrreps == numIrreps, "numIrreps");
    CHECK(table->classes == classes, "classes pointer");
    CHECK(table->irreps == irreps, "irreps pointer");

    // freeCharacterTable frees the classes array, irreps array, and values (2D). It does not
    // free the individual irreps nor individual classes. We must free those separately.
    for (int k = 0; k < numIrreps; k++) freeCharacter(irreps[k]);
    for (int i = 0; i < n; i++) freeConjugacyClass(classes[i]);
    freeCharacterTable(table);

    freeCharacterTable(NULL);
    CHECK(1, "freeCharacterTable(NULL) safe");

    freeGroup(Z2);
}

/* ---------- Tests for derived representation constructors ---------- */

// Verify that a Representation is a homomorphism: rho(g_i * g_j) == rho(g_i) * rho(g_j)
static bool checkHomomorphism(Representation* rep, double tol) {
    if (!rep) return false;
    Group* G = rep->group;
    for (int i = 0; i < G->card; i++) {
        for (int j = 0; j < G->card; j++) {
            int k = G->table[i][j];
            Matrix* P = multiplyMatrices(rep->images[i], rep->images[j]);
            if (!P) return false;
            bool ok = matrixComp(P, rep->images[k], tol);
            freeMatrix(P);
            if (!ok) return false;
        }
    }
    return true;
}

// Check rho(identity) == I_dim
static bool checkIdentityImage(Representation* rep, double tol) {
    Matrix* I = idMatrix(rep->dim);
    bool ok = matrixComp(rep->images[0], I, tol);
    freeMatrix(I);
    return ok;
}

void testGet1Dreps() {
    SECTION("get1Dreps");

    int count = -1;
    CHECK(get1Dreps(NULL, &count) == NULL, "NULL group");
    CHECK(get1Dreps(constructZnGroup(2), NULL) == NULL || 1, "NULL count handled");

    // Z_n abelian: should give exactly n linear characters
    Group* Z4 = constructZnGroup(4);
    Representation** reps = get1Dreps(Z4, &count);
    CHECK(reps != NULL, "Z4: get1Dreps returns array");
    CHECK(count == 4, "Z4: 4 linear characters");

    // Each is a homomorphism of dim 1, with rho(0) = 1
    bool allOk = true;
    for (int r = 0; r < count; r++) {
        if (reps[r]->dim != 1 || reps[r]->mdim != 1) allOk = false;
        if (!checkIdentityImage(reps[r], 1e-9)) allOk = false;
        if (!checkHomomorphism(reps[r], 1e-9)) allOk = false;
    }
    CHECK(allOk, "Z4: all reps are 1D homomorphisms with rho(e)=1");

    // For Z_4, the four characters chi_k(j) = exp(2πi * k * j / 4). The
    // sum over a full orbit (k != 0) should be zero.
    bool orthogonal = true;
    for (int r = 0; r < count; r++) {
        ComplexNumber sum = {0.0, 0.0};
        for (int j = 0; j < Z4->card; j++) {
            MatrixElement e = getEntry(reps[r]->images[j], 0, 0);
            ComplexNumber c = elemToComplex(e);
            sum = complexAdd(sum, c);
        }
        // Trivial char: sum = |G|. Nontrivial: sum = 0.
        bool trivialish = fabs(sum.real - 4.0) < 1e-6 && fabs(sum.imag) < 1e-6;
        bool zero = fabs(sum.real) < 1e-6 && fabs(sum.imag) < 1e-6;
        if (!(trivialish || zero)) orthogonal = false;
    }
    CHECK(orthogonal, "Z4: column sums are |G| (trivial) or 0 (nontrivial)");

    for (int r = 0; r < count; r++) freeRepresentation(reps[r]);
    free(reps);
    freeGroup(Z4);

    // S_3: |S3/[S3,S3]| = |Z2| = 2 linear characters
    Group* S3 = constructSymmetricGroup(3);
    reps = get1Dreps(S3, &count);
    CHECK(reps != NULL && count == 2, "S3: exactly 2 linear characters");
    // One should be the trivial rep; the other the sign rep.
    bool foundTrivial = false, foundSign = false;
    for (int r = 0; r < count; r++) {
        bool allOnes = true;
        bool isSign = true;
        for (int g = 0; g < S3->card; g++) {
            MatrixElement e = getEntry(reps[r]->images[g], 0, 0);
            ComplexNumber c = elemToComplex(e);
            if (!(fabs(c.real - 1.0) < 1e-6 && fabs(c.imag) < 1e-6)) allOnes = false;
            // Sign: +-1 only
            if (!((fabs(c.real - 1.0) < 1e-6 || fabs(c.real + 1.0) < 1e-6)
                  && fabs(c.imag) < 1e-6)) isSign = false;
        }
        if (allOnes) foundTrivial = true;
        else if (isSign) foundSign = true;
    }
    CHECK(foundTrivial, "S3: trivial char present");
    CHECK(foundSign, "S3: sign char present");

    for (int r = 0; r < count; r++) freeRepresentation(reps[r]);
    free(reps);
    freeGroup(S3);
}

void testTensorProduct() {
    SECTION("tensorProduct");

    CHECK(tensorProduct(NULL, NULL) == NULL, "NULL inputs");

    Group* S3 = constructSymmetricGroup(3);
    Representation* std = standardRepresentation(S3);
    Representation* triv = trivialRepresentation(S3);

    // V (x) trivial should be V (up to dimension and equality)
    Representation* prod = tensorProduct(std, triv);
    CHECK(prod != NULL, "S3: std (x) trivial constructed");
    CHECK(prod->dim == std->dim, "dim(V (x) trivial) = dim V");
    bool eq = true;
    for (int i = 0; i < S3->card; i++) {
        if (!matrixComp(prod->images[i], std->images[i], 1e-9)) eq = false;
    }
    CHECK(eq, "V (x) trivial == V");
    CHECK(checkHomomorphism(prod, 1e-9), "tensorProduct image is a homomorphism");
    CHECK(checkIdentityImage(prod, 1e-9), "tensorProduct rho(e) = I");

    freeRepresentation(prod);

    // V (x) V on S3: dim 4
    Representation* sq = tensorProduct(std, std);
    CHECK(sq != NULL, "S3: std (x) std built");
    CHECK(sq->dim == std->dim * std->dim, "dim std (x) std = (dim std)^2");
    CHECK(checkHomomorphism(sq, 1e-9), "std (x) std homomorphism");
    freeRepresentation(sq);

    freeRepresentation(std);
    freeRepresentation(triv);
    freeGroup(S3);
}

void testSymmetricAndWedgeProduct() {
    SECTION("symmetricProduct / wedgeProduct");

    CHECK(symmetricProduct(NULL) == NULL, "sym: NULL");
    CHECK(wedgeProduct(NULL) == NULL, "wedge: NULL");

    Group* S3 = constructSymmetricGroup(3);
    Representation* std = standardRepresentation(S3);  // dim 2

    // Sym^2 of dim 2 has dim 3
    Representation* sym = symmetricProduct(std);
    CHECK(sym != NULL, "S3: Sym^2(std) built");
    CHECK(sym->dim == 3, "Sym^2 of 2-dim rep has dim 3");
    CHECK(checkIdentityImage(sym, 1e-9), "Sym^2 rho(e) = I");
    CHECK(checkHomomorphism(sym, 1e-9), "Sym^2 is a homomorphism");

    // Wedge^2 of dim 2 has dim 1; should be the sign rep on S3
    Representation* wedge = wedgeProduct(std);
    CHECK(wedge != NULL, "S3: Wedge^2(std) built");
    CHECK(wedge->dim == 1, "Wedge^2 of 2-dim rep has dim 1");
    CHECK(checkIdentityImage(wedge, 1e-9), "Wedge^2 rho(e) = I");
    CHECK(checkHomomorphism(wedge, 1e-9), "Wedge^2 is a homomorphism");

    // Trace of sym + trace of wedge = (trace V)^2  (for any g)
    bool traceOk = true;
    for (int g = 0; g < S3->card; g++) {
        MatrixElement tV = trace(std->images[g]);
        MatrixElement tS = trace(sym->images[g]);
        MatrixElement tW = trace(wedge->images[g]);
        ComplexNumber tVc = elemToComplex(tV);
        ComplexNumber tSc = elemToComplex(tS);
        ComplexNumber tWc = elemToComplex(tW);
        // (trace V)^2 = trace Sym + trace Wedge
        ComplexNumber sq = complexMul(tVc, tVc);
        ComplexNumber sw = complexAdd(tSc, tWc);
        if (!complexEq(sq, sw, 1e-7)) traceOk = false;
    }
    CHECK(traceOk, "chi_V^2 = chi_{Sym^2} + chi_{Wedge^2}");

    // Symmetric square trace identity: chi_{Sym^2 V}(g) = (chi_V(g)^2 + chi_V(g^2)) / 2
    // and chi_{Wedge^2 V}(g) = (chi_V(g)^2 - chi_V(g^2)) / 2
    bool symId = true, wedgeId = true;
    for (int g = 0; g < S3->card; g++) {
        int g2 = S3->table[g][g];
        MatrixElement tV = trace(std->images[g]);
        MatrixElement tV2 = trace(std->images[g2]);
        ComplexNumber a = elemToComplex(tV);
        ComplexNumber b = elemToComplex(tV2);
        ComplexNumber a2 = complexMul(a, a);
        ComplexNumber sumS = { (a2.real + b.real) / 2.0, (a2.imag + b.imag) / 2.0 };
        ComplexNumber sumW = { (a2.real - b.real) / 2.0, (a2.imag - b.imag) / 2.0 };
        ComplexNumber tS = elemToComplex(trace(sym->images[g]));
        ComplexNumber tW = elemToComplex(trace(wedge->images[g]));
        if (!complexEq(tS, sumS, 1e-7)) symId = false;
        if (!complexEq(tW, sumW, 1e-7)) wedgeId = false;
    }
    CHECK(symId, "chi_{Sym^2}(g) = (chi(g)^2 + chi(g^2)) / 2");
    CHECK(wedgeId, "chi_{Wedge^2}(g) = (chi(g)^2 - chi(g^2)) / 2");

    freeRepresentation(sym);
    freeRepresentation(wedge);
    freeRepresentation(std);
    freeGroup(S3);
}

void testCrossProductReps() {
    SECTION("crossProductReps");

    CHECK(crossProductReps(NULL, NULL, NULL) == NULL, "NULL inputs");

    Group* Z2 = constructZnGroup(2);
    Group* Z3 = constructZnGroup(3);
    Group* Z2xZ3 = constructProductGroup(Z2, Z3);

    Representation* trivZ2 = trivialRepresentation(Z2);
    Representation* trivZ3 = trivialRepresentation(Z3);

    // trivial (><) trivial = trivial on the product
    Representation* prod = crossProductReps(trivZ2, trivZ3, Z2xZ3);
    CHECK(prod != NULL, "Z2 x Z3: trivial (><) trivial");
    CHECK(prod->dim == 1, "1D x 1D = 1D");
    CHECK(checkHomomorphism(prod, 1e-9), "homomorphism on Z2 x Z3");
    freeRepresentation(prod);

    // regular (><) trivial = regular-on-Z2 lifted to Z2xZ3
    Representation* regZ2 = regularRepresentation(Z2);
    prod = crossProductReps(regZ2, trivZ3, Z2xZ3);
    CHECK(prod != NULL, "regZ2 (><) trivZ3 built");
    CHECK(prod->dim == 2, "dim = 2");
    CHECK(checkHomomorphism(prod, 1e-9), "regZ2 (><) trivZ3 is a homomorphism");
    freeRepresentation(prod);

    freeRepresentation(regZ2);
    freeRepresentation(trivZ2);
    freeRepresentation(trivZ3);
    freeGroup(Z2xZ3);
    freeGroup(Z2);
    freeGroup(Z3);
}

void testInducedRepresentation() {
    SECTION("inducedRepresentation");

    CHECK(inducedRepresentation(NULL, NULL) == NULL, "NULL inputs");

    // Induce trivial from H={e} in Z3 up to Z3 -> regular rep of Z3
    Group* Z3 = constructZnGroup(3);
    int* trivIdx = malloc(sizeof(int));
    trivIdx[0] = 0;
    SubGroup* H = constructSubgroup(Z3, trivIdx, 1);
    Group* Hgroup = trivialGroup();

    Representation* trivH = trivialRepresentation(Hgroup);
    Representation* ind = inducedRepresentation(trivH, H);
    CHECK(ind != NULL, "Z3: ind from {e} built");
    CHECK(ind->dim == 3, "dim of induced = [G:H] * dim V = 3");
    CHECK(checkIdentityImage(ind, 1e-9), "induced rho(e) = I");
    CHECK(checkHomomorphism(ind, 1e-9), "induced is a homomorphism");

    // Compare to regular rep: same character (same trace at each g)
    Representation* reg = regularRepresentation(Z3);
    bool sameTrace = true;
    for (int g = 0; g < Z3->card; g++) {
        ComplexNumber a = elemToComplex(trace(ind->images[g]));
        ComplexNumber b = elemToComplex(trace(reg->images[g]));
        if (!complexEq(a, b, 1e-9)) sameTrace = false;
    }
    CHECK(sameTrace, "Ind_e^G trivial has same character as regular rep");

    freeRepresentation(ind);
    freeRepresentation(reg);
    freeRepresentation(trivH);
    freeGroup(Hgroup);
    freeSubgroup(H);
    freeGroup(Z3);
}

/* ---------- Tests for additional rep / group helpers ---------- */

void testSubgroupAsGroup() {
    SECTION("subgroupAsGroup");

    CHECK(subgroupAsGroup(NULL) == NULL, "NULL input");

    // The whole group of S3 as SubGroup -> Group of order 6
    Group* S3 = constructSymmetricGroup(3);
    int* allIdx = malloc(S3->card * sizeof(int));
    for (int i = 0; i < S3->card; i++) allIdx[i] = i;
    SubGroup* H = constructSubgroup(S3, allIdx, S3->card);
    CHECK(H != NULL, "S3 itself as SubGroup");

    Group* Hg = subgroupAsGroup(H);
    CHECK(Hg != NULL, "subgroupAsGroup built");
    CHECK(Hg->card == S3->card, "card preserved");

    // Identity at index 0
    bool idAt0 = isGroupIdentity(Hg, Hg->elements[0]);
    CHECK(idAt0, "identity at index 0 of new Group");

    freeGroup(Hg);
    freeSubgroup(H);
    freeGroup(S3);
}

void testProjectToAbelianization() {
    SECTION("projectToAbelianization");

    CHECK(projectToAbelianization(NULL) == NULL, "NULL input");

    // S3 -> Z2: nontrivial cosets are {even, odd}, image of (12) is the nontrivial elt
    Group* S3 = constructSymmetricGroup(3);
    GroupHomomorphism* hom = projectToAbelianization(S3);
    CHECK(hom != NULL, "S3 abelianization built");
    CHECK(hom->codomain->card == 2, "S3^ab has order 2");
    CHECK(hom->mapping[0] == 0, "identity maps to identity coset");

    // Image of an even permutation should be 0; odd -> nonzero coset
    int* perm = malloc(3 * sizeof(int));
    for (int i = 0; i < 3; i++) perm[i] = i;
    bool ok = true;
    for (int idx = 0; idx < S3->card; idx++) {
        int s = permSign(perm, 3); // 0 even, 1 odd
        int img = hom->mapping[idx];
        if (s == 0 && img != 0) ok = false;
        if (s == 1 && img == 0) ok = false;
        if (idx + 1 < S3->card) nextPermutation(perm, 3);
    }
    free(perm);
    CHECK(ok, "S3 -> S3^ab is the sign map");

    Group* Q = hom->codomain;
    freeGroupHomomorphism(hom);
    freeGroup(Q);
    freeGroup(S3);

    // Z4 abelian: abelianization is Z4, projection is identity
    Group* Z4 = constructZnGroup(4);
    hom = projectToAbelianization(Z4);
    CHECK(hom != NULL, "Z4 abelianization built");
    CHECK(hom->codomain->card == 4, "Z4^ab = Z4");
    Q = hom->codomain;
    freeGroupHomomorphism(hom);
    freeGroup(Q);
    freeGroup(Z4);
}

void testSignRepresentation() {
    SECTION("signRepresentation");

    CHECK(signRepresentation(NULL) == NULL, "NULL input");

    Group* S3 = constructSymmetricGroup(3);
    Representation* sgn = signRepresentation(S3);
    CHECK(sgn != NULL, "S3: sign rep built");
    CHECK(sgn->dim == 1, "sign rep is 1D");
    CHECK(checkIdentityImage(sgn, 1e-12), "sign(e) = 1");
    CHECK(checkHomomorphism(sgn, 1e-12), "sign is a homomorphism");

    // Trace identity: sign equals (-1)^{permSign}; verified by recomputing
    int* perm = malloc(3 * sizeof(int));
    for (int i = 0; i < 3; i++) perm[i] = i;
    bool valuesOk = true;
    for (int idx = 0; idx < S3->card; idx++) {
        double expected = (permSign(perm, 3) == 0) ? 1.0 : -1.0;
        if (!approxReal(getEntry(sgn->images[idx], 0, 0), expected, 1e-12)) valuesOk = false;
        if (idx + 1 < S3->card) nextPermutation(perm, 3);
    }
    free(perm);
    CHECK(valuesOk, "sign rep matches permSign on every element");

    // Sign rep should equal Wedge^2(standard) for S3 (both 1D, same character)
    Representation* std = standardRepresentation(S3);
    Representation* w = wedgeProduct(std);
    bool same = true;
    for (int g = 0; g < S3->card; g++) {
        if (!matrixComp(sgn->images[g], w->images[g], 1e-9)) same = false;
    }
    CHECK(same, "S3: sgn = Wedge^2(std)");
    freeRepresentation(std);
    freeRepresentation(w);

    freeRepresentation(sgn);
    freeGroup(S3);

    // S4: 24 elements, 12 even (sign +1), 12 odd (sign -1)
    Group* S4 = constructSymmetricGroup(4);
    sgn = signRepresentation(S4);
    CHECK(sgn != NULL && sgn->dim == 1, "S4: sign rep built");
    CHECK(checkHomomorphism(sgn, 1e-12), "S4: sign is a homomorphism");
    int plus = 0, minus = 0;
    for (int g = 0; g < S4->card; g++) {
        double v = realOf(getEntry(sgn->images[g], 0, 0));
        if (v > 0) plus++; else minus++;
    }
    CHECK(plus == 12 && minus == 12, "S4: 12 even and 12 odd");
    freeRepresentation(sgn);
    freeGroup(S4);
}

void testDualRepresentation() {
    SECTION("dualRepresentation");

    CHECK(dualRepresentation(NULL) == NULL, "NULL input");

    Group* S3 = constructSymmetricGroup(3);
    Representation* std = standardRepresentation(S3);
    Representation* dual = dualRepresentation(std);
    CHECK(dual != NULL, "S3: dual built");
    CHECK(dual->dim == std->dim, "dim preserved");
    CHECK(checkIdentityImage(dual, 1e-9), "dual(e) = I");
    CHECK(checkHomomorphism(dual, 1e-9), "dual is a homomorphism");

    // chi_{V*}(g) = chi_V(g^{-1})
    bool charOk = true;
    for (int g = 0; g < S3->card; g++) {
        int gInv = -1;
        for (int x = 0; x < S3->card; x++) if (S3->table[g][x] == 0) { gInv = x; break; }
        ComplexNumber a = elemToComplex(trace(dual->images[g]));
        ComplexNumber b = elemToComplex(trace(std->images[gInv]));
        if (!complexEq(a, b, 1e-9)) charOk = false;
    }
    CHECK(charOk, "chi_{V*}(g) = chi_V(g^{-1})");

    // Self-dual for S3 standard: traces match (S3 chars are real)
    bool selfDual = true;
    for (int g = 0; g < S3->card; g++) {
        ComplexNumber a = elemToComplex(trace(dual->images[g]));
        ComplexNumber b = elemToComplex(trace(std->images[g]));
        if (!complexEq(a, b, 1e-9)) selfDual = false;
    }
    CHECK(selfDual, "S3 std is self-dual at the character level");

    freeRepresentation(dual);
    freeRepresentation(std);
    freeGroup(S3);
}

void testConjugateRepresentation() {
    SECTION("conjugateRepresentation");

    CHECK(conjugateRepresentation(NULL) == NULL, "NULL input");

    // For Z3, the nontrivial 1D rep takes a primitive cube root of unity zeta;
    // its conjugate takes zeta^2. Verify this for one of the get1Dreps reps.
    Group* Z3 = constructZnGroup(3);
    int count = 0;
    Representation** reps = get1Dreps(Z3, &count);
    Representation* nontrivial = NULL;
    for (int r = 0; r < count; r++) {
        ComplexNumber c = elemToComplex(getEntry(reps[r]->images[1], 0, 0));
        if (fabs(c.imag) > 1e-6) { nontrivial = reps[r]; break; }
    }
    CHECK(nontrivial != NULL, "Z3: complex 1D rep located");

    Representation* conj = conjugateRepresentation(nontrivial);
    CHECK(conj != NULL, "Z3: conjugate built");
    CHECK(checkIdentityImage(conj, 1e-9), "conj(e) = I");
    CHECK(checkHomomorphism(conj, 1e-9), "conjugate is a homomorphism");

    // Entries are complex conjugates of the original
    bool conjOk = true;
    for (int g = 0; g < Z3->card; g++) {
        ComplexNumber orig = elemToComplex(getEntry(nontrivial->images[g], 0, 0));
        ComplexNumber c = elemToComplex(getEntry(conj->images[g], 0, 0));
        if (!complexEq(c, complexConj(orig), 1e-9)) conjOk = false;
    }
    CHECK(conjOk, "Z3: entries are complex conjugates");

    freeRepresentation(conj);
    for (int r = 0; r < count; r++) freeRepresentation(reps[r]);
    free(reps);
    freeGroup(Z3);

    // Real rep (S3 std) should be unchanged by conjugation
    Group* S3 = constructSymmetricGroup(3);
    Representation* std = standardRepresentation(S3);
    Representation* stdConj = conjugateRepresentation(std);
    bool same = true;
    for (int g = 0; g < S3->card; g++) {
        if (!matrixComp(std->images[g], stdConj->images[g], 1e-9)) same = false;
    }
    CHECK(same, "S3: conjugate of real-valued rep equals itself");
    freeRepresentation(stdConj);
    freeRepresentation(std);
    freeGroup(S3);
}

/* ---------- Main ---------- */

int main(void) {
    testConstructAndFreeConjugacyClass();
    testGetConjugacyClass();
    testGetConjugacyClasses();
    testConstructAndFreeRepresentation();
    testTrivialRepresentation();
    testRegularRepresentation();
    testPermutationRepresentation();
    testStandardRepresentation();
    testConstructAndFreeCharacter();
    testConstructAndFreeCharacterTable();
    testGet1Dreps();
    testTensorProduct();
    testSymmetricAndWedgeProduct();
    testCrossProductReps();
    testInducedRepresentation();
    testSubgroupAsGroup();
    testProjectToAbelianization();
    testSignRepresentation();
    testDualRepresentation();
    testConjugateRepresentation();

    printf("\n==============================\n");
    printf("Tests: %d/%d passed\n", testsPassed, testsRun);
    printf("==============================\n");
    return (testsPassed == testsRun) ? 0 : 1;
}
