
/* AI GENERATED TEST SUITE */

// Everything here looks good to me, but note this was generated by an LLM.
// More tests might be warranted if using for production.

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
#include "hebi.h"
#include "sokko.h"
#include "usagi.h"
#include "tora.h"

/* ---------- Test infrastructure ---------- */

static int testsRun = 0;
static int testsPassed = 0;

#define CHECK(cond, name) do { \
    testsRun++; \
    if (cond) { testsPassed++; printf("  [PASS] %s\n", name); } \
    else { printf("  [FAIL] %s (line %d)\n", name, __LINE__); } \
} while (0)

#define SECTION(name) printf("\n=== %s ===\n", name)

static double realOf(MatrixElement e) {
    return e.isComplex ? e.value.complex.real : e.value.real;
}

static bool approxReal(MatrixElement e, double expected, double tol) {
    double actual = realOf(e);
    return fabs(actual - expected) <= tol;
}

/* ---------- ConjugacyClass tests ---------- */

void testConstructAndFreeConjugacyClass() {
    SECTION("constructConjugacyClass / freeConjugacyClass");
    Group* Z4 = constructZnGroup(4);

    // NULL inputs
    CHECK(constructConjugacyClass(NULL, Z4->elements[0]) == NULL, "construct: NULL group");
    CHECK(constructConjugacyClass(Z4, NULL) == NULL, "construct: NULL rep");

    // Identity is its own class in any group
    ConjugacyClass* cls = constructConjugacyClass(Z4, Z4->elements[0]);
    CHECK(cls != NULL, "construct identity class");
    CHECK(cls->group == Z4, "class group pointer");
    CHECK(cls->rep == Z4->elements[0], "class rep pointer");
    CHECK(cls->size == 1, "identity class size is 1");
    CHECK(cls->elementOrder == 1, "identity element order is 1");
    CHECK(cls->indices != NULL, "class indices allocated");
    freeConjugacyClass(cls);

    // element of order 2 in Z4
    ConjugacyClass* cls2 = constructConjugacyClass(Z4, Z4->elements[2]);
    CHECK(cls2 != NULL, "construct order-2 class");
    CHECK(cls2->size == 1, "Z4: each class has size 1 (abelian)");
    CHECK(cls2->elementOrder == 2, "element 2 has order 2 in Z4");
    freeConjugacyClass(cls2);

    // free(NULL) should be safe
    freeConjugacyClass(NULL);
    CHECK(1, "freeConjugacyClass(NULL) does not crash");

    freeGroup(Z4);
}

void testGetConjugacyClass() {
    SECTION("getConjugacyClass");
    Group* Z3 = constructZnGroup(3);

    CHECK(getConjugacyClass(NULL) == NULL, "getConjugacyClass: NULL");

    ConjugacyClass* cls = getConjugacyClass(Z3->elements[1]);
    CHECK(cls != NULL, "getConjugacyClass produces class");
    CHECK(cls->rep == Z3->elements[1], "class rep matches");
    CHECK(cls->size == 1, "Z3 abelian: class size 1");
    freeConjugacyClass(cls);

    freeGroup(Z3);
}

void testGetConjugacyClasses() {
    SECTION("getConjugacyClasses");
    int n;

    CHECK(getConjugacyClasses(NULL, &n) == NULL, "NULL group");

    // Abelian: every element is its own class
    Group* Z5 = constructZnGroup(5);
    ConjugacyClass** classes = getConjugacyClasses(Z5, &n);
    CHECK(classes != NULL, "Z5: got classes");
    CHECK(n == 5, "Z5: has 5 conjugacy classes");
    int totalSize = 0;
    for (int i = 0; i < n; i++) totalSize += classes[i]->size;
    CHECK(totalSize == 5, "Z5: sum of class sizes = |G|");
    for (int i = 0; i < n; i++) freeConjugacyClass(classes[i]);
    free(classes);
    freeGroup(Z5);

    // S_3: 3 conjugacy classes of sizes 1, 3, 2
    Group* S3 = constructSymmetricGroup(3);
    classes = getConjugacyClasses(S3, &n);
    CHECK(classes != NULL, "S3: got classes");
    CHECK(n == 3, "S3: has 3 conjugacy classes");
    int sum = 0;
    for (int i = 0; i < n; i++) sum += classes[i]->size;
    CHECK(sum == 6, "S3: sum of class sizes = 6");
    for (int i = 0; i < n; i++) freeConjugacyClass(classes[i]);
    free(classes);
    freeGroup(S3);
}

/* ---------- Representation tests ---------- */

// Build a small Matrix** manually for testing construct/free
static Matrix** makeIdentityImages(int count, int dim) {
    Matrix** imgs = malloc(count * sizeof(Matrix*));
    for (int i = 0; i < count; i++) imgs[i] = idMatrix(dim);
    return imgs;
}

void testConstructAndFreeRepresentation() {
    SECTION("constructRepresentation / freeRepresentation");
    Group* Z2 = constructZnGroup(2);

    CHECK(constructRepresentation(NULL, "X", NULL, 1, 1) == NULL, "NULL inputs");

    Matrix** imgs = makeIdentityImages(Z2->card, 2);
    Representation* rep = constructRepresentation(Z2, "Test", imgs, 2, 2);
    CHECK(rep != NULL, "rep constructed");
    CHECK(rep->group == Z2, "rep->group correct");
    CHECK(rep->images == imgs, "rep->images correct");
    CHECK(rep->mdim == 2, "rep->mdim set");
    CHECK(rep->dim == 2, "rep->dim set");
    CHECK(strcmp(rep->repr, "Test") == 0, "rep->repr copied");
    freeRepresentation(rep);

    freeRepresentation(NULL);
    CHECK(1, "freeRepresentation(NULL) safe");

    freeGroup(Z2);
}

void testTrivialRepresentation() {
    SECTION("trivialRepresentation");
    CHECK(trivialRepresentation(NULL) == NULL, "NULL group");

    Group* Z4 = constructZnGroup(4);
    Representation* rep = trivialRepresentation(Z4);
    CHECK(rep != NULL, "rep built");
    CHECK(rep->dim == 1, "trivial dim = 1");
    CHECK(rep->mdim == 1, "trivial mdim = 1");
    for (int i = 0; i < Z4->card; i++) {
        CHECK(approxReal(getEntry(rep->images[i], 0, 0), 1.0, 1e-12),
              "trivial image is [1]");
    }
    freeRepresentation(rep);
    freeGroup(Z4);
}

void testRegularRepresentation() {
    SECTION("regularRepresentation");
    CHECK(regularRepresentation(NULL) == NULL, "NULL group");

    Group* Z3 = constructZnGroup(3);
    Representation* rep = regularRepresentation(Z3);
    CHECK(rep != NULL, "rep built");
    CHECK(rep->dim == 3, "regular dim = |G|");
    CHECK(rep->mdim == 3, "regular mdim = |G|");

    // Identity image should be the identity matrix
    Matrix* I = rep->images[0];
    bool identityOk = true;
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++) {
            double expected = (i == j) ? 1.0 : 0.0;
            if (!approxReal(getEntry(I, i, j), expected, 1e-12)) identityOk = false;
        }
    CHECK(identityOk, "regular rep of identity is I");

    // Each image is a permutation matrix: each row/col has exactly one 1
    bool permOk = true;
    for (int g = 0; g < Z3->card; g++) {
        for (int i = 0; i < 3; i++) {
            int rowOnes = 0, colOnes = 0;
            for (int j = 0; j < 3; j++) {
                if (approxReal(getEntry(rep->images[g], i, j), 1.0, 1e-12)) rowOnes++;
                if (approxReal(getEntry(rep->images[g], j, i), 1.0, 1e-12)) colOnes++;
            }
            if (rowOnes != 1 || colOnes != 1) permOk = false;
        }
    }
    CHECK(permOk, "each regular image is a permutation matrix");

    freeRepresentation(rep);
    freeGroup(Z3);
}

void testPermutationRepresentation() {
    SECTION("permutationRepresentation");
    CHECK(permutationRepresentation(NULL) == NULL, "NULL group");

    // S_3: permutation rep should have dim equal to index of the largest core-free subgroup (= 3)
    Group* S3 = constructSymmetricGroup(3);
    Representation* rep = permutationRepresentation(S3);
    CHECK(rep != NULL, "S3: perm rep built");
    CHECK(rep->dim >= 1 && rep->dim <= S3->card, "S3: perm rep dim sensible");

    // Identity element must map to identity matrix
    Matrix* I = rep->images[0];
    bool identityOk = true;
    for (int i = 0; i < rep->dim; i++)
        for (int j = 0; j < rep->dim; j++) {
            double expected = (i == j) ? 1.0 : 0.0;
            if (!approxReal(getEntry(I, i, j), expected, 1e-12)) identityOk = false;
        }
    CHECK(identityOk, "S3: perm rep of identity is I");
    freeRepresentation(rep);
    freeGroup(S3);
}

void testStandardRepresentation() {
    SECTION("standardRepresentation");
    CHECK(standardRepresentation(NULL) == NULL, "NULL group");

    Group* S3 = constructSymmetricGroup(3);
    Representation* rep = standardRepresentation(S3);
    CHECK(rep != NULL, "S3: standard rep built");
    // Standard rep of S_n has dim n-1; with perm rep dim 3 we expect dim 2
    CHECK(rep->dim >= 1, "S3: standard dim >= 1");

    // Identity must still be identity
    Matrix* I = rep->images[0];
    bool identityOk = true;
    for (int i = 0; i < rep->dim; i++)
        for (int j = 0; j < rep->dim; j++) {
            double expected = (i == j) ? 1.0 : 0.0;
            if (!approxReal(getEntry(I, i, j), expected, 1e-12)) identityOk = false;
        }
    CHECK(identityOk, "S3: standard rep of identity is I");

    freeRepresentation(rep);
    freeGroup(S3);
}

/* ---------- Character tests ---------- */

void testConstructAndFreeCharacter() {
    SECTION("constructCharacter / freeCharacter");
    Group* Z3 = constructZnGroup(3);
    int n;
    ConjugacyClass** classes = getConjugacyClasses(Z3, &n);
    ComplexNumber* values = malloc(n * sizeof(ComplexNumber));
    for (int i = 0; i < n; i++) { values[i].real = 1.0; values[i].imag = 0.0; }

    CHECK(constructCharacter(NULL, "x", classes, values, n) == NULL, "NULL group");
    CHECK(constructCharacter(Z3, NULL, classes, values, n) == NULL, "NULL repr");
    CHECK(constructCharacter(Z3, "x", NULL, values, n) == NULL, "NULL classes");
    CHECK(constructCharacter(Z3, "x", classes, NULL, n) == NULL, "NULL values");

    Character* chi = constructCharacter(Z3, "trivial", classes, values, n);
    CHECK(chi != NULL, "character constructed");
    CHECK(chi->group == Z3, "group pointer");
    CHECK(chi->classes == classes, "classes pointer");
    CHECK(chi->values == values, "values pointer");
    CHECK(chi->numClasses == n, "numClasses stored");
    CHECK(strcmp(chi->repr, "trivial") == 0, "repr copied");

    // freeCharacter frees classes (array), values, repr — but not class contents
    // So we must free individual classes first, then let freeCharacter handle the array
    for (int i = 0; i < n; i++) freeConjugacyClass(classes[i]);
    freeCharacter(chi);

    freeCharacter(NULL);
    CHECK(1, "freeCharacter(NULL) safe");

    freeGroup(Z3);
}

/* ---------- CharacterTable tests ---------- */

void testConstructAndFreeCharacterTable() {
    SECTION("constructCharacterTable / freeCharacterTable");
    Group* Z2 = constructZnGroup(2);
    int n;
    ConjugacyClass** classes = getConjugacyClasses(Z2, &n);

    // Two irreducible characters for Z2
    int numIrreps = n;
    Character** irreps = malloc(numIrreps * sizeof(Character*));
    for (int k = 0; k < numIrreps; k++) {
        ComplexNumber* v = malloc(n * sizeof(ComplexNumber));
        for (int i = 0; i < n; i++) { v[i].real = (k == 0) ? 1.0 : ((i == 0) ? 1.0 : -1.0); v[i].imag = 0.0; }
        // Character takes ownership of v. But we also need a classes pointer — pass the shared
        // array. We will NOT let freeCharacter free the shared classes; so instead construct a
        // per-character copy of the array.
        ConjugacyClass** classesCopy = malloc(n * sizeof(ConjugacyClass*));
        for (int i = 0; i < n; i++) classesCopy[i] = classes[i];
        irreps[k] = constructCharacter(Z2, "chi", classesCopy, v, n);
    }

    ComplexNumber** values = malloc(numIrreps * sizeof(ComplexNumber*));
    for (int i = 0; i < numIrreps; i++) {
        values[i] = malloc(n * sizeof(ComplexNumber));
        for (int j = 0; j < n; j++) {
            values[i][j].real = irreps[i]->values[j].real;
            values[i][j].imag = 0.0;
        }
    }

    CHECK(constructCharacterTable(NULL, classes, irreps, values, n, numIrreps) == NULL, "NULL group");
    CHECK(constructCharacterTable(Z2, NULL, irreps, values, n, numIrreps) == NULL, "NULL classes");
    CHECK(constructCharacterTable(Z2, classes, NULL, values, n, numIrreps) == NULL, "NULL irreps");
    CHECK(constructCharacterTable(Z2, classes, irreps, NULL, n, numIrreps) == NULL, "NULL values");

    CharacterTable* table = constructCharacterTable(Z2, classes, irreps, values, n, numIrreps);
    CHECK(table != NULL, "table constructed");
    CHECK(table->group == Z2, "table group");
    CHECK(table->numClasses == n, "numClasses");
    CHECK(table->numIrreps == numIrreps, "numIrreps");
    CHECK(table->classes == classes, "classes pointer");
    CHECK(table->irreps == irreps, "irreps pointer");

    // freeCharacterTable frees the classes array, irreps array, and values (2D). It does not
    // free the individual irreps nor individual classes. We must free those separately.
    for (int k = 0; k < numIrreps; k++) freeCharacter(irreps[k]);
    for (int i = 0; i < n; i++) freeConjugacyClass(classes[i]);
    freeCharacterTable(table);

    freeCharacterTable(NULL);
    CHECK(1, "freeCharacterTable(NULL) safe");

    freeGroup(Z2);
}

/* ---------- Main ---------- */

int main(void) {
    testConstructAndFreeConjugacyClass();
    testGetConjugacyClass();
    testGetConjugacyClasses();
    testConstructAndFreeRepresentation();
    testTrivialRepresentation();
    testRegularRepresentation();
    testPermutationRepresentation();
    testStandardRepresentation();
    testConstructAndFreeCharacter();
    testConstructAndFreeCharacterTable();

    printf("\n==============================\n");
    printf("Tests: %d/%d passed\n", testsPassed, testsRun);
    printf("==============================\n");
    return (testsPassed == testsRun) ? 0 : 1;
}
